"""nba schedule warehouse

Revision ID: 0c5935bfa513
Revises: bdb013473c1a
Create Date: 2026-08-11 15:07:02.506773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5935bfa513'
down_revision: Union[str, Sequence[str], None] = 'bdb013473c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_teams',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nba_team_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('abbreviation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nba_teams')),
    sa.UniqueConstraint('nba_team_id', name=op.f('uq_nba_teams_nba_team_id'))
    )
    op.create_table('nba_games',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nba_game_id', sa.Text(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['nba_teams.id'], name=op.f('fk_nba_games_away_team_id_nba_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['nba_teams.id'], name=op.f('fk_nba_games_home_team_id_nba_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nba_games')),
    sa.UniqueConstraint('nba_game_id', name=op.f('uq_nba_games_nba_game_id'))
    )
    op.create_index(op.f('ix_nba_games_away_team_id'), 'nba_games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_nba_games_game_date'), 'nba_games', ['game_date'], unique=False)
    op.create_index(op.f('ix_nba_games_home_team_id'), 'nba_games', ['home_team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nba_games_home_team_id'), table_name='nba_games')
    op.drop_index(op.f('ix_nba_games_game_date'), table_name='nba_games')
    op.drop_index(op.f('ix_nba_games_away_team_id'), table_name='nba_games')
    op.drop_table('nba_games')
    op.drop_table('nba_teams')
    # ### end Alembic commands ###
