"""player projections warehouse

Revision ID: 0c78fbbd5f0f
Revises: 38e1e360f829
Create Date: 2026-08-11 23:00:03.412204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c78fbbd5f0f'
down_revision: Union[str, Sequence[str], None] = '38e1e360f829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_projections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nba_player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('projected_games', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Float(), nullable=False),
    sa.Column('fga', sa.Float(), nullable=False),
    sa.Column('ftm', sa.Float(), nullable=False),
    sa.Column('fta', sa.Float(), nullable=False),
    sa.Column('tpm', sa.Float(), nullable=False),
    sa.Column('pts', sa.Float(), nullable=False),
    sa.Column('reb', sa.Float(), nullable=False),
    sa.Column('ast', sa.Float(), nullable=False),
    sa.Column('stl', sa.Float(), nullable=False),
    sa.Column('blk', sa.Float(), nullable=False),
    sa.Column('tov', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nba_player_id'], ['nba_players.id'], name=op.f('fk_player_projections_nba_player_id_nba_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_projections')),
    sa.UniqueConstraint('nba_player_id', 'season', 'source', name=op.f('uq_player_projections_nba_player_id'))
    )
    op.create_index(op.f('ix_player_projections_nba_player_id'), 'player_projections', ['nba_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_projections_nba_player_id'), table_name='player_projections')
    op.drop_table('player_projections')
    # ### end Alembic commands ###
