"""league free agents

Revision ID: 18df7247b119
Revises: a5ab6113da02
Create Date: 2026-09-12 12:21:08.888992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18df7247b119'
down_revision: Union[str, Sequence[str], None] = 'a5ab6113da02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_free_agents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('nba_player_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('waiver_date', sa.Date(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_league_free_agents_league_id_leagues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nba_player_id'], ['nba_players.id'], name=op.f('fk_league_free_agents_nba_player_id_nba_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_league_free_agents')),
    sa.UniqueConstraint('league_id', 'nba_player_id', name=op.f('uq_league_free_agents_league_id'))
    )
    op.create_index(op.f('ix_league_free_agents_league_id'), 'league_free_agents', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_free_agents_nba_player_id'), 'league_free_agents', ['nba_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_free_agents_nba_player_id'), table_name='league_free_agents')
    op.drop_index(op.f('ix_league_free_agents_league_id'), table_name='league_free_agents')
    op.drop_table('league_free_agents')
    # ### end Alembic commands ###
