"""player stats warehouse and yahoo nba id mapping

Revision ID: 38e1e360f829
Revises: 65cb464f1186
Create Date: 2026-08-11 22:52:49.717676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e1e360f829'
down_revision: Union[str, Sequence[str], None] = '65cb464f1186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_players',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nba_person_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('nba_team_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nba_team_id'], ['nba_teams.id'], name=op.f('fk_nba_players_nba_team_id_nba_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nba_players')),
    sa.UniqueConstraint('nba_person_id', name=op.f('uq_nba_players_nba_person_id'))
    )
    op.create_index(op.f('ix_nba_players_full_name'), 'nba_players', ['full_name'], unique=False)
    op.create_index(op.f('ix_nba_players_nba_team_id'), 'nba_players', ['nba_team_id'], unique=False)
    op.create_table('player_id_maps',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nba_player_id', sa.BigInteger(), nullable=True),
    sa.Column('yahoo_player_key', sa.Text(), nullable=False),
    sa.Column('yahoo_name', sa.Text(), nullable=False),
    sa.Column('match_method', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nba_player_id'], ['nba_players.id'], name=op.f('fk_player_id_maps_nba_player_id_nba_players'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_id_maps')),
    sa.UniqueConstraint('yahoo_player_key', name=op.f('uq_player_id_maps_yahoo_player_key'))
    )
    op.create_index(op.f('ix_player_id_maps_nba_player_id'), 'player_id_maps', ['nba_player_id'], unique=False)
    op.create_table('player_season_averages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nba_player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Float(), nullable=False),
    sa.Column('fga', sa.Float(), nullable=False),
    sa.Column('ftm', sa.Float(), nullable=False),
    sa.Column('fta', sa.Float(), nullable=False),
    sa.Column('tpm', sa.Float(), nullable=False),
    sa.Column('pts', sa.Float(), nullable=False),
    sa.Column('reb', sa.Float(), nullable=False),
    sa.Column('ast', sa.Float(), nullable=False),
    sa.Column('stl', sa.Float(), nullable=False),
    sa.Column('blk', sa.Float(), nullable=False),
    sa.Column('tov', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nba_player_id'], ['nba_players.id'], name=op.f('fk_player_season_averages_nba_player_id_nba_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_season_averages')),
    sa.UniqueConstraint('nba_player_id', 'season', name=op.f('uq_player_season_averages_nba_player_id'))
    )
    op.create_index(op.f('ix_player_season_averages_nba_player_id'), 'player_season_averages', ['nba_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_season_averages_nba_player_id'), table_name='player_season_averages')
    op.drop_table('player_season_averages')
    op.drop_index(op.f('ix_player_id_maps_nba_player_id'), table_name='player_id_maps')
    op.drop_table('player_id_maps')
    op.drop_index(op.f('ix_nba_players_nba_team_id'), table_name='nba_players')
    op.drop_index(op.f('ix_nba_players_full_name'), table_name='nba_players')
    op.drop_table('nba_players')
    # ### end Alembic commands ###
