"""core schema

Revision ID: bdb013473c1a
Revises: 
Create Date: 2026-08-11 14:31:20.997355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdb013473c1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('yahoo_league_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('scoring_type', sa.Text(), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('yahoo_league_key', name=op.f('uq_leagues_yahoo_league_key'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('yahoo_guid', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('yahoo_guid', name=op.f('uq_users_yahoo_guid'))
    )
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('yahoo_team_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_users_team', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_teams_league_id_leagues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teams_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('yahoo_team_key', name=op.f('uq_teams_yahoo_team_key'))
    )
    op.create_index(op.f('ix_teams_league_id'), 'teams', ['league_id'], unique=False)
    op.create_index(op.f('ix_teams_user_id'), 'teams', ['user_id'], unique=False)
    op.create_table('yahoo_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_yahoo_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yahoo_tokens')),
    sa.UniqueConstraint('user_id', name=op.f('uq_yahoo_tokens_user_id'))
    )
    op.create_table('roster_slots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('yahoo_player_key', sa.Text(), nullable=False),
    sa.Column('player_name', sa.Text(), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('injury_status', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_roster_slots_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster_slots'))
    )
    op.create_index(op.f('ix_roster_slots_team_id'), 'roster_slots', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_slots_team_id'), table_name='roster_slots')
    op.drop_table('roster_slots')
    op.drop_table('yahoo_tokens')
    op.drop_index(op.f('ix_teams_user_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_league_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('users')
    op.drop_table('leagues')
    # ### end Alembic commands ###
